config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    resources :grades
    resources :subjects
    resources :teachers
    resources :parents
    resources :students
  end

  resources :lessons
  resources :journals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parent.rb
# == Schema Information
#
# Table name: parents
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_parents_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Parent < ApplicationRecord
  belongs_to :user

  has_many :students

  delegate :email, :full_name, :address, to: :user
end

app/controllers/admin/parents_controller.rb
class Admin::ParentsController < Admin::ApplicationController
  before_action :set_parent, only: %i[show edit update destroy]

  def index
    @parents = Parent.all
  end

  def show;  end

  def new
    @parent = Parent.new
  end

  def create
    @parent = Parent.new(parent_params)

    if @parent.save
      redirect_to admin_parents_path
    else
      render :new
    end

  end

  def edit;  end

  def update
    if @parent.update(parent_params)
      redirect_to [:admin, @parent]
    else
      render :edit
    end
  end

  def destroy
    @parent.destroy

    redirect_to admin_parents_path
  end

  private

  def set_parent
    @parent = Parent.find(params[:id])
  end

  def parent_params
    params.require(:parent).permit(:user_id)
  end
end

app/views/admin/parents/_actions.html.erb
<td><%= link_to t('.show'), admin_parent_path(parent.id) %></td>
<td><%= link_to t('.edit'), edit_admin_parent_path(parent.id) %></td>
<td><%= link_to t('.delete'), admin_parent_path(parent.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>

app/views/admin/parents/_form.html.erb
<h2><%= action_name == 'new' ? 'New' : 'Edit' %> <%= t('.parents_title') %></h2>
<br>
<div class="container">
  <%= simple_form_for [:admin, @parent], defaults: { input_html: { class: 'form-control' } } do |f| %>
    <%= f.association :user, as: :select, label_method: :full_name, value_method: :id, include_blank: false %>
    <%= f.submit "save", class: "actions btn btn-primary" %>
  <% end %>
  <hr>
  <div class="col-md-3"><%= link_to t('.back'), admin_parents_path, class: "btn btn-primary" %></div>
</div>

app/views/admin/parents/_parent.html.erb
  <tr>
    <td><%= parent.full_name %></td>
    <td><%= parent.address %></td>
    <td><%= parent.email %></td>
    <td><%= parent.created_at.strftime("%B %d, %Y") %></td>
    <%= render partial: 'admin/parents/actions', locals: {parent: parent} %>
  </tr>

app/views/admin/parents/edit.html.erb
<%= render "form" %>

app/views/admin/parents/index.html.erb
<h1 class="text-center"><%= t('.parents') %></h1>
<div class="container">
  <table class="table table-striped text-center">
    <thead class="thead-dark">
    <tr>
      <th scope="col"><%= t('.full_name')%></th>
      <th scope="col"><%= t('.address')%></th>
      <th scope="col"><%= t('.email')%></th>
      <th scope="col"><%= t('.time') %></th>
      <th colspan=3 scope="col"><%= t('.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'parent', collection: @parents %>
    </tbody>
  </table>
  <hr>
</div>

<%= link_to t('.add_new_parent'), new_admin_parent_path, class: "btn btn-primary" %>

app/views/admin/parents/new.html.erb
<%= render "form" %>

app/views/admin/parents/show.html.erb
<div class="container">
  <div class="col-md">
    <h2 class="text-center"><%= t('.parent') %></h2>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col"><%= t('.full_name')%></th>
        <th scope="col"><%= t('.address')%></th>
        <th scope="col"><%= t('.email')%></th>
        <th scope="col"><%= t('.time') %></th>
        <th colspan=2 scope="col"><%= t('.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @parent.full_name %></td>
        <td><%= @parent.address %></td>
        <td><%= @parent.email %></td>
        <td><%= @parent.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to t('.edit'), edit_admin_parent_path(@parent.id) %></td>
        <td><%= link_to t('.delete'), admin_parent_path(@parent.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to t('.back'), admin_parents_path, class: "btn btn-primary" %>