config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    resources :grades
    resources :subjects
    resources :teachers
    resources :parents
    resources :students
  end

  resources :lessons
  resources :journals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id         :bigint           not null, primary key
#  birthday   :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  grade_id   :bigint           not null
#  parent_id  :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_students_on_grade_id   (grade_id)
#  index_students_on_parent_id  (parent_id)
#  index_students_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (grade_id => grades.id)
#  fk_rails_...  (parent_id => parents.id)
#  fk_rails_...  (user_id => users.id)
#
class Student < ApplicationRecord
  belongs_to :user
  belongs_to :grade
  belongs_to :parent

  delegate :email, :full_name, :address, to: :user
  delegate :grade_group, to: :grade
  validates :birthday, presence: true
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::ApplicationController
  before_action :set_student, only: %i[show edit update destroy]

  def index
    @students = Student.all
  end

  def show;  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to admin_students_path
    else
      render :new
    end

  end

  def edit;  end

  def update
    if @student.update(student_params)
      redirect_to [:admin, @student]
    else
      render :edit
    end
  end

  def destroy
    @student.destroy

    redirect_to admin_students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:birthday, :user_id, :parent_id, :grade_id )
  end
end

app/views/admin/students/_actions.html.erb
<td><%= link_to t('.show'), admin_student_path(student.id) %></td>
<td><%= link_to t('.edit'), edit_admin_student_path(student.id) %></td>
<td><%= link_to t('.delete'), admin_student_path(student.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>

app/views/admin/students/_form.html.erb
<h2><%= action_name == 'new' ? 'New' : 'Edit' %> <%= t('.students_title') %></h2>
<br>
<div class="container">
  <%= simple_form_for [:admin, @student], defaults: { input_html: { class: 'form-control' } } do |f| %>
    <%= f.association :user, as: :select, label_method: :full_name, value_method: :id, include_blank: false %>
    <%= f.input :birthday, as: :date,
                start_year: Time.now.year - 90,
                end_year: Time.now.year - 8,
                order: [:day, :month, :year],
                html5: true,
                placeholder: t('.birthday') %>
    <%= f.association :parent, as: :select, label_method: :full_name, value_method: :id, include_blank: false %>
    <%= f.association :grade, as: :select,  label_method: :grade_group, value_method: :id, include_blank: false %>
    <%= f.submit "save", class: "actions btn btn-primary" %>
  <% end %>
  <hr>
  <div class="col-md-3"><%= link_to t('.back'), admin_students_path, class: "btn btn-primary" %></div>
</div>

app/views/admin/students/_student.html.erb
  <tr>
    <td><%= student.full_name %></td>
    <td><%= student.address %></td>
    <td><%= student.email %></td>
    <td><%= student.birthday %></td>
    <td><%= student.grade_group %></td>
    <td><%= student.parent.full_name %></td>
    <td><%= student.created_at.strftime("%B %d, %Y") %></td>
    <%= render partial: 'admin/students/actions', locals: {student: student} %>
  </tr>

app/views/admin/students/edit.html.erb
<%= render "form" %>

app/views/admin/students/index.html.erb
<h1 class="text-center"><%= t('.students') %></h1>
<div class="container">
  <table class="table table-striped text-center">
    <thead class="thead-dark">
    <tr>
      <th scope="col"><%= t('.full_name')%></th>
      <th scope="col"><%= t('.address')%></th>
      <th scope="col"><%= t('.email')%></th>
      <th scope="col"><%= t('.birthday')%></th>
      <th scope="col"><%= t('.grade')%></th>
      <th scope="col"><%= t('.parent')%></th>
      <th scope="col"><%= t('.time') %></th>
      <th colspan=3 scope="col"><%= t('.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'student', collection: @students %>
    </tbody>
  </table>
  <hr>
</div>

<%= link_to t('.add_new_student'), new_admin_student_path, class: "btn btn-primary" %>

app/views/admin/students/new.html.erb
<%= render "form" %>

app/views/admin/students/show.html.erb
<div class="container">
  <div class="col-md">
    <h2 class="text-center"><%= t('.student') %></h2>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col"><%= t('.full_name')%></th>
        <th scope="col"><%= t('.address')%></th>
        <th scope="col"><%= t('.email')%></th>
        <th scope="col"><%= t('.birthday')%></th>
        <th scope="col"><%= t('.grade')%></th>
        <th scope="col"><%= t('.parent')%></th>
        <th scope="col"><%= t('.time') %></th>
        <th colspan=2 scope="col"><%= t('.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @student.full_name %></td>
        <td><%= @student.address %></td>
        <td><%= @student.email %></td>
        <td><%= @student.birthday %></td>
        <td><%= @student.grade_group %></td>
        <td><%= @student.parent.full_name %></td>
        <td><%= @student.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to t('.edit'), edit_admin_student_path(@student.id) %></td>
        <td><%= link_to t('.delete'), admin_student_path(@student.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to t('.back'), admin_parents_path, class: "btn btn-primary" %>