config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    resources :grades
    resources :subjects
    resources :teachers
    resources :parents
    resources :students
  end

  resources :lessons
  resources :journals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Subject < ApplicationRecord
  has_many :lessons
  has_many :teachers
  validates :name,
            presence: true
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    @subjects = Subject.all
  end

  def show; end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to admin_subjects_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update(subject_params)
      redirect_to [:admin, @subject]
    else
      render 'edit'
    end
  end

  def destroy
    @subject.destroy

    redirect_to admin_subjects_path
  end

  private

   def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[show edit update destroy]

  def index
    @subjects = Subject.all
  end

  def show; end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject
    else
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update(subject_params)
      redirect_to @subject
    else
      render 'edit'
    end
  end

  def destroy
    @subject.destroy

    redirect_to subjects_path
  end

  private

   def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/views/subjects/_subject.html.erb
  <tr>
    <td><%= subject.name %></td>
    <td><%= subject.created_at.strftime("%B %d, %Y") %></td>
    <%= render partial: 'subjects/actions', locals: {subject: subject} %>
  </tr>

app/views/subjects/index.html.erb
<h1 class="text-center"><%= t('.subjects') %></h1>
<div class="container">
  <table class="table table-striped text-center">
    <thead class="thead-dark">
    <tr>
      <th scope="col"><%= t('.name')%></th>
      <th scope="col"><%= t('.time') %></th>
      <th colspan=3 scope="col"><%= t('.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'subject', collection: @subjects %>
    </tbody>
  </table>
  <hr>
</div>

<%= link_to t('.add_new_subject'), new_subject_path, class: "btn btn-primary" %>

app/views/subjects/show.html.erb
<div class="container">
  <div class="col-md-9">
    <h2 class="text-center"><%= t('.subject') %></h2>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col"><%= t('.name') %></th>
        <th scope="col"><%= t('.time') %></th>
        <th colspan=2 scope="col"><%= t('.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @subject.name %></td>
        <td><%= @subject.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to t('.edit'), edit_subject_path(@subject.id) %></td>
        <td><%= link_to t('.delete'), subject_path(@subject.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to t('.back'), subjects_path, class: "btn btn-primary" %>