config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    resources :grades
    resources :subjects
    resources :teachers
    resources :parents
    resources :students
  end

  resources :lessons
  resources :journals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id          :bigint           not null, primary key
#  date_at     :date
#  description :string
#  home_task   :string
#  number      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  grade_id    :bigint           not null
#  subject_id  :bigint           not null
#  teacher_id  :bigint           not null
#
# Indexes
#
#  index_lessons_on_grade_id    (grade_id)
#  index_lessons_on_subject_id  (subject_id)
#  index_lessons_on_teacher_id  (teacher_id)
#
# Foreign Keys
#
#  fk_rails_...  (grade_id => grades.id)
#  fk_rails_...  (subject_id => subjects.id)
#  fk_rails_...  (teacher_id => teachers.id)
#
class Lesson < ApplicationRecord
  START_NUMBER = 1
  END_NUMBER = 9

  belongs_to :subject
  belongs_to :grade
  belongs_to :teacher

  has_many :rates

  validates :date_at, :home_task, :description, :number, presence: true
  validates :number, inclusion: START_NUMBER..END_NUMBER
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_lesson, only: %i[show edit update destroy]

  def index
    @lessons = Lesson.all
  end

  def show;  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end

  end

  def edit;  end

  def update
    if @lesson.update(lesson_params)
      redirect_to @lesson
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy

    redirect_to lessons_path
  end

  private

  def authenticate_teacher!
    return if current_user&.teacher

    redirect_to root_path, alert: 'You are not allowed!' if current_user
    redirect_to new_user_session_path if !current_user
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:home_task, :description, :date_at, :subject_id, :grade_id, :teacher_id, :number)
  end
end

app/views/lessons/_actions.html.erb
<td><%= link_to t('.show'), lesson_path(lesson.id) %></td>
<td><%= link_to t('.edit'), edit_lesson_path(lesson.id) %></td>
<td><%= link_to t('.delete'), lesson_path(lesson.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>

app/views/lessons/_form.html.erb
<h2><%= action_name == 'new' ? 'New' : 'Edit' %> <%= t('.lessons_title') %></h2>
<br>
<div class="container">
  <%= simple_form_for @lesson, defaults: { input_html: { class: 'form-control' } } do |f| %>
    <%= f.association :teacher, as: :select, label_method: :full_name, value_method: :id, include_blank: false %>
    <%= f.association :subject, as: :select, value_method: :id, include_blank: false %>
    <%= f.association :grade, as: :select,  label_method: :grade_group, value_method: :id, include_blank: false %>
    <%= f.input :home_task, placeholder: t('.home_task') %>
    <%= f.input :description, placeholder: t('.description') %>
    <%= f.input :date_at, as: :date,
                start_year: Time.now.year,
                end_year: Time.now.year + 12,
                order: [:day, :month, :year],
                html5: true,
                placeholder: t('.date_at') %>
    <%= f.submit "save", class: "actions btn btn-primary" %>
  <% end %>
  <hr>
  <div class="col-md-3"><%= link_to t('.back'), lessons_path, class: "btn btn-primary" %></div>
</div>

app/views/lessons/_lesson.html.erb
  <tr>
    <td><%= lesson.teacher.full_name %></td>
    <td><%= lesson.subject.name %></td>
    <td><%= lesson.grade.grade_group %></td>
    <td><%= lesson.home_task %></td>
    <td><%= lesson.description %></td>
    <td><%= lesson.date_at %></td>
    <td><%= lesson.created_at.strftime("%B %d, %Y") %></td>
    <%= render partial: 'lessons/actions', locals: {lesson: lesson} %>
  </tr>

app/views/lessons/edit.html.erb
<%= render "form" %>

app/views/lessons/index.html.erb
<h1 class="text-center"><%= t('.lessons') %></h1>
<div class="container">
  <table class="table table-striped text-center">
    <thead class="thead-dark">
    <tr>
      <th scope="col"><%= t('.teacher')%></th>
      <th scope="col"><%= t('.subject')%></th>
      <th scope="col"><%= t('.grade')%></th>
      <th scope="col"><%= t('.home_task')%></th>
      <th scope="col"><%= t('.description')%></th>
      <th scope="col"><%= t('.date_at')%></th>
      <th scope="col"><%= t('.time') %></th>
      <th colspan=3 scope="col"><%= t('.actions') %></th>
    </tr>
    </thead>
    <tbody>
    <%= render partial: 'lesson', collection: @lessons %>
    </tbody>
  </table>
  <hr>
</div>

<%= link_to t('.add_new_lesson'), new_lesson_path, class: "btn btn-primary" %>

app/views/lessons/new.html.erb
<%= render "form" %>

app/views/lessons/show.html.erb
<div class="container">
  <div class="col-md">
    <h2 class="text-center"><%= t('.lesson') %></h2>
    <table class="table table-striped">
      <thead class="thead-dark">
      <tr>
        <th scope="col"><%= t('.teacher')%></th>
        <th scope="col"><%= t('.subject')%></th>
        <th scope="col"><%= t('.grade')%></th>
        <th scope="col"><%= t('.home_task')%></th>
        <th scope="col"><%= t('.description')%></th>
        <th scope="col"><%= t('.date_at')%></th>
        <th scope="col"><%= t('.time') %></th>
        <th colspan=3 scope="col"><%= t('.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @lesson.teacher.full_name %></td>
        <td><%= @lesson.subject.name %></td>
        <td><%= @lesson.grade.grade_group %></td>
        <td><%= @lesson.home_task %></td>
        <td><%= @lesson.description %></td>
        <td><%= @lesson.date_at %></td>
        <td><%= @lesson.created_at.strftime("%B %d, %Y") %></td>
        <td><%= link_to t('.edit'), edit_lesson_path(@lesson.id) %></td>
        <td><%= link_to t('.delete'), lesson_path(@lesson.id), method: :delete, data: { confirm: t('.are_you_sure') } %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<br>
<%= link_to t('.back'), lessons_path, class: "btn btn-primary" %>